2020-09-05 21:52:44,772 INFO: Microblog startup [in /home/aaron/Code/flask-book/app/__init__.py:45]
2020-09-05 22:28:54,973 INFO: Microblog startup [in /home/aaron/Code/flask-book/app/__init__.py:45]
2020-09-05 22:30:05,016 INFO: Microblog startup [in /home/aaron/Code/flask-book/app/__init__.py:45]
2020-09-05 22:30:14,192 INFO: Microblog startup [in /home/aaron/Code/flask-book/app/__init__.py:45]
2020-09-05 22:30:22,927 INFO: Microblog startup [in /home/aaron/Code/flask-book/app/__init__.py:45]
2020-09-05 22:30:28,534 INFO: Microblog startup [in /home/aaron/Code/flask-book/app/__init__.py:45]
2020-09-05 22:35:29,487 INFO: Microblog startup [in /home/aaron/Code/flask-book/app/__init__.py:45]
2020-09-05 22:35:36,976 INFO: Microblog startup [in /home/aaron/Code/flask-book/app/__init__.py:45]
2020-09-05 22:35:45,219 INFO: Microblog startup [in /home/aaron/Code/flask-book/app/__init__.py:45]
2020-09-05 22:36:05,963 INFO: Microblog startup [in /home/aaron/Code/flask-book/app/__init__.py:45]
2020-09-06 12:46:30,770 INFO: Microblog startup [in /home/aaron/Code/flask-book/app/__init__.py:45]
2020-09-06 12:46:54,385 INFO: Microblog startup [in /home/aaron/Code/flask-book/app/__init__.py:45]
2020-09-06 14:36:33,537 INFO: Microblog startup [in /home/aaron/Code/flask-book/app/__init__.py:45]
2020-09-06 14:37:41,048 INFO: Microblog startup [in /home/aaron/Code/flask-book/app/__init__.py:45]
2020-09-06 14:39:01,026 INFO: Microblog startup [in /home/aaron/Code/flask-book/app/__init__.py:45]
2020-09-06 14:40:29,382 INFO: Microblog startup [in /home/aaron/Code/flask-book/app/__init__.py:45]
2020-09-06 14:42:00,220 INFO: Microblog startup [in /home/aaron/Code/flask-book/app/__init__.py:45]
2020-09-06 14:42:17,171 INFO: Microblog startup [in /home/aaron/Code/flask-book/app/__init__.py:45]
2020-09-06 14:42:35,360 INFO: Microblog startup [in /home/aaron/Code/flask-book/app/__init__.py:45]
2020-09-06 14:49:56,071 INFO: Microblog startup [in /home/aaron/Code/flask-book/app/__init__.py:45]
2020-09-06 14:50:05,025 INFO: Microblog startup [in /home/aaron/Code/flask-book/app/__init__.py:45]
2020-09-06 14:50:30,307 INFO: Microblog startup [in /home/aaron/Code/flask-book/app/__init__.py:45]
2020-09-06 14:50:38,228 INFO: Microblog startup [in /home/aaron/Code/flask-book/app/__init__.py:45]
2020-09-06 14:50:53,148 INFO: Microblog startup [in /home/aaron/Code/flask-book/app/__init__.py:45]
2020-09-06 14:52:55,537 INFO: Microblog startup [in /home/aaron/Code/flask-book/app/__init__.py:45]
2020-09-06 14:52:58,321 INFO: Microblog startup [in /home/aaron/Code/flask-book/app/__init__.py:45]
2020-09-06 14:53:04,025 INFO: Microblog startup [in /home/aaron/Code/flask-book/app/__init__.py:45]
2020-09-06 14:55:42,598 INFO: Microblog startup [in /home/aaron/Code/flask-book/app/__init__.py:45]
2020-09-06 15:14:16,890 INFO: Microblog startup [in /home/aaron/Code/flask-book/app/__init__.py:45]
2020-09-06 16:15:44,605 ERROR: Exception on /user/amy [GET] [in /home/aaron/Code/flask-book/venv/lib/python3.8/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/aaron/Code/flask-book/venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/aaron/Code/flask-book/venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/aaron/Code/flask-book/venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/aaron/Code/flask-book/venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/aaron/Code/flask-book/venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/aaron/Code/flask-book/venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/aaron/Code/flask-book/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/aaron/Code/flask-book/app/routes.py", line 76, in user
    return render_template('user.html', user=user, posts=posts)
  File "/home/aaron/Code/flask-book/venv/lib/python3.8/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/home/aaron/Code/flask-book/venv/lib/python3.8/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/aaron/Code/flask-book/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/aaron/Code/flask-book/venv/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/aaron/Code/flask-book/venv/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/aaron/Code/flask-book/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/aaron/Code/flask-book/app/templates/base.html", line 30, in top-level template code
    {% block content %}{% endblock %}
  File "/home/aaron/Code/flask-book/app/templates/user.html", line 11, in block "content"
    <p>{{ user.followers.count() }} followers, {{ user.followed.count() }} following</p>
  File "/home/aaron/Code/flask-book/venv/lib/python3.8/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'app.models.User object' has no attribute 'followers'
2020-09-06 18:20:43,980 INFO: Microblog startup [in /home/aaron/Code/flask-book/app/__init__.py:45]
